name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, edited, ready_for_review]

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  test-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft)
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m venv .venv
          chmod +x .venv/bin/activate
          .venv/bin/activate
      - name: Install dependencies
        run: |
          make install
          cd docs
          pip install -r requirements.txt
      - name: Build Docs
        run: |
          cd docs
          make html SPHINXOPTS="-W"

  test:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft)
    env:
      ALTADB_API_KEY: ${{ secrets.ALTADB_API_KEY }}
      ALTADB_SECRET_KEY: ${{ secrets.ALTADB_SECRET_KEY }}
      ALTADB_URL: ${{ secrets.ALTADB_URL }}
      ALTADB_ORG_ID: ${{ secrets.ALTADB_ORG_ID }}
      ALTADB_SDK_SOURCE: GITHUB
      ALTADB_SDK_DEBUG: 1
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m venv .venv
      - run: |
          chmod +x .venv/bin/activate
          .venv/bin/activate
        if: matrix.os == 'ubuntu-latest'
      - run: |
          chmod +x .venv/bin/activate
          source .venv/bin/activate
        if: matrix.os == 'macos-latest'
      - run: .venv\Scripts\activate
        if: matrix.os == 'windows-latest'
      - name: Install dependencies
        run: make install
      - name: Lint + Unit Tests
        run: make test
